### ISSUE TITLE
ucenter.html

### ISSUE THREAD

**Issue by ctisssproject** [stevensmx5/Germany#2]
`<h2>欢迎你：<a href=""><span>刘浩</span></a></h2>`

是鼠标触碰出现下划线，目前的样子，是默认已经有下划线了。

**Comment by ctisssproject** [comment]
`<a href="">
                    <div class="right_btn">
                        <img alt="" src="images/option.png" />
                        <p>修改个人资料</p>
                    </div>
                </a>
                <a href="">
                    <div class="right_btn">
                        <img alt="" src="images/key_b.png" />
                        <p>修改密码</p>
                    </div>
                </a>`

这两个鼠标触碰后，出现下划线。

**Comment by stevensmx5** [comment]
修改完成
